version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pb_data:/pb_data
    env_file:
      - .env
    ports:
      - "8090:8090"
    command: "/docker-gs-ping serve"
    restart: "always"
